---
# tasks file for ec2_stop

- name: Stop specified EC2 instances
  amazon.aws.ec2_instance:
    state: stopped
    instance_ids:
      - i-07028663bfb34d0b5 # Replace with your instance ID(s)
    region: us-west-2  # Replace with your desired region
    aws_access_key: "{{ ec2_access_key }}"
    aws_secret_key: "{{ ec2_secret_key }}"

