---
# tasks file for ec2
- name: Launch an EC2 instance in the default VPC
  amazon.aws.ec2_instance:
    name: "ansible-instance"
    instance_type: t2.micro
    image_id: ami-0c6d358ee9e264ff1
    region: ca-central-1
    aws_access_key: "{{ ec2_access_key }}"
    aws_secret_key: "{{ ec2_secret_key }}"
    network:
      assign_public_ip: yes  # This is optional but will be default behavior in default VPC
    tags:
      Name: Testing
